from pathlib import Path

# Adjust to wherever the drive is actually mounted on this machine.
LIBRARY_ROOT = Path("/mnt/game-library")

# Converted .nsp files land here, keyed by game id, so a title is only
# ever decompressed once no matter how many times it's downloaded.
# The source library itself is never written to.
#
# Defaults to a path under the current user's home directory rather
# than /var/lib/ specifically so `python server.py` works unprivileged,
# which is how this has been tested throughout. If you deploy this via
# games-galore-server.service instead, that unit's `StateDirectory=`
# directive creates and owns /var/lib/games-galore-server for you
# automatically — in that case, point this at
# /var/lib/games-galore-server/cache instead and you won't need sudo
# for that either, since systemd sets it up ahead of the service ever
# running.
CACHE_DIR = Path.home() / ".cache" / "games-galore-server"

# How large the conversion cache may grow before the least recently
# used .nsp files are swept out of it. Everything in there can be
# regenerated by decompressing again, so the only cost of evicting too
# eagerly is CPU on the next download of that title — which is why this
# can be set as low as the disk requires. A decompressed .nsp is roughly
# twice its .nsz, so this holds perhaps a dozen large Switch titles.
CACHE_MAX_BYTES = 40 * 1024 * 1024 * 1024

# Cloud saves live here, one directory per game, each holding a handful
# of timestamped archives. Deliberately NOT under CACHE_DIR: everything
# in there can be regenerated from the library by decompressing again,
# whereas a save is the only copy of someone's progress. Losing the
# cache costs CPU; losing this costs the playthrough. Point it at
# something you actually back up.
SAVE_ROOT = Path.home() / ".local" / "share" / "games-galore-server" / "saves"

# How many versions of a game's save to keep before the oldest is
# pruned. The point of keeping more than one is recovering from a bad
# sync — an overwrite by a stale device, a crash mid-write — which is
# only useful if you notice within a few sessions.
SAVE_VERSIONS_KEPT = 10

# Where these two lived before the project settled on one name. A
# checkout that is simply updated would otherwise start writing to a
# fresh directory and appear to have lost every stored save, so the
# server moves them across once, on startup, if the new path doesn't
# exist yet. Delete these and the migration once no deployment is old
# enough to need it.
LEGACY_CACHE_DIR = Path.home() / ".cache" / "vault-server"
LEGACY_SAVE_ROOT = Path.home() / ".local" / "share" / "vault-server" / "saves"

# How long a cached catalog is trusted before it is rescanned anyway.
# The directory-mtime check catches games added, removed or renamed
# within a fraction of a second; this is the backstop for a file edited
# in place several levels down, which no cheap check can see. POST
# /rescan forces one immediately.
CATALOG_TTL_SECONDS = 10 * 60

# Shared secret for the save endpoints, which are the only writable
# surface this server exposes. Empty means no check at all, which is
# the default because a LAN tool that refuses to work until it is
# configured is a LAN tool nobody configures — but note what the
# difference actually is: with this unset, anyone who can reach the
# port can read, overwrite and grow your saves, while everything else
# here is read-only. Set it to any long random string (`openssl rand
# -hex 32`) and put the same value in the client's Settings.
SAVE_TOKEN = ""

HOST = "0.0.0.0"
PORT = 8420
