import os
from pathlib import Path

# Where the games are. Adjust to wherever the drive is actually
# mounted on this machine.
#
# List more than one and the library spans them: each is scanned in
# order and the results are one catalog, so a second drive can simply
# be added when the first fills up. A title present on two drives is
# taken from the first one listed, which is what makes moving games
# between drives safe to do while the server is running — the copy
# being made is ignored until the old one is gone.
#
# The environment wins where it is set, which suits a systemd unit:
#   LIBRARY_ROOTS=/mnt/game-library:/mnt/game-library-2
LIBRARY_ROOTS = [
    Path("/mnt/game-library"),
    # Path("/mnt/game-library-2"),
]

if os.environ.get("LIBRARY_ROOTS"):
    LIBRARY_ROOTS = [
        Path(part) for part in os.environ["LIBRARY_ROOTS"].split(os.pathsep) if part
    ]

# What a single-drive install called it, and still may: a config.py
# edited before there could be several is read for this name instead.
LIBRARY_ROOT = LIBRARY_ROOTS[0]

# Converted .nsp files land here, keyed by game id, so a title is only
# ever decompressed once no matter how many times it's downloaded.
# The source library itself is never written to.
#
# Defaults to a path under the current user's home directory rather
# than /var/lib/ specifically so `python server.py` works unprivileged,
# which is how this has been tested throughout. If you deploy this via
# games-galore-server.service instead, that unit's `StateDirectory=`
# directive creates and owns /var/lib/games-galore-server for you
# automatically — in that case, point this at
# /var/lib/games-galore-server/cache instead and you won't need sudo
# for that either, since systemd sets it up ahead of the service ever
# running.
CACHE_DIR = Path.home() / ".cache" / "games-galore-server"

# How large the conversion cache may grow before the least recently
# used .nsp files are swept out of it. Everything in there can be
# regenerated by decompressing again, so the only cost of evicting too
# eagerly is CPU on the next download of that title — which is why this
# can be set as low as the disk requires. A decompressed .nsp is roughly
# twice its .nsz, so this holds perhaps a dozen large Switch titles.
CACHE_MAX_BYTES = 40 * 1024 * 1024 * 1024

# Cloud saves live here, one directory per game, each holding a handful
# of timestamped archives. Deliberately NOT under CACHE_DIR: everything
# in there can be regenerated from the library by decompressing again,
# whereas a save is the only copy of someone's progress. Losing the
# cache costs CPU; losing this costs the playthrough. Point it at
# something you actually back up.
SAVE_ROOT = Path.home() / ".local" / "share" / "games-galore-server" / "saves"

# How many versions of a game's save to keep before the oldest is
# pruned. The point of keeping more than one is recovering from a bad
# sync — an overwrite by a stale device, a crash mid-write — which is
# only useful if you notice within a few sessions.
SAVE_VERSIONS_KEPT = 10

# Where these two lived before the project settled on one name. A
# checkout that is simply updated would otherwise start writing to a
# fresh directory and appear to have lost every stored save, so the
# server moves them across once, on startup, if the new path doesn't
# exist yet. Delete these and the migration once no deployment is old
# enough to need it.
LEGACY_CACHE_DIR = Path.home() / ".cache" / "vault-server"
LEGACY_SAVE_ROOT = Path.home() / ".local" / "share" / "vault-server" / "saves"

# How long a cached catalog is trusted before it is rescanned anyway.
# The directory-mtime check catches games added, removed or renamed
# within a fraction of a second; this is the backstop for a file edited
# in place several levels down, which no cheap check can see. POST
# /rescan forces one immediately.
CATALOG_TTL_SECONDS = 10 * 60

# RAWG (https://rawg.io/apidocs) is where the metadata fetcher gets
# descriptions, cover art, screenshots and trailers. A free key is
# instant and generous enough for a personal library.
#
# Read from the environment first so a key never has to be committed:
#   RAWG_API_KEY=... .venv/bin/python server.py
RAWG_API_KEY = os.environ.get("RAWG_API_KEY", "")

# Screenshots to keep per game. RAWG often has a dozen; the detail view
# shows a strip of thumbnails, and past half a dozen nobody scrolls.
METADATA_MAX_SCREENSHOTS = 6

# Shared secret for the save endpoints, which are the only writable
# surface this server exposes. Empty means no check at all, which is
# the default because a LAN tool that refuses to work until it is
# configured is a LAN tool nobody configures — but note what the
# difference actually is: with this unset, anyone who can reach the
# port can read, overwrite and grow your saves, while everything else
# here is read-only. Set it to any long random string (`openssl rand
# -hex 32`) and put the same value in the client's Settings.
SAVE_TOKEN = ""

HOST = "0.0.0.0"
PORT = 8420
